### ISSUE TITLE
Helper 'get_action' has not been defined

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-faociok#14]
`get_action `helper method has been deprecated and returns a server error.

```
File '/usr/lib/ckan/default/src/ckanext-faociok/ckanext/faociok/templates/home/snippets/organizations.html', line 2 in top-level template code
  {% set groups = h.get_action('organization_list', {'limit': 4, 'all_fields': True, 'sort': 'package_count'}) or h.get_action('organization_list', {'limit': 4, 'all_fields': True}) %}
File '/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py', line 412 in getattr
  return obj[attribute]
File '/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py', line 72 in __getitem__
  key=key
HelperError: Helper 'get_action' has not been defined.
```

**Comment by cezio** [comment]
It seems `helpers.get_action()` was removed in 2.6. Since it wasn't specified which version we target, I was using 2.5 as a reference version.

Fix is in progress.

**Comment by cezio** [comment]
I just realized, that in order to fix this, we'd need to override `/home` controller (we need to inject extra variables for home for customized snippets, which are included in layout template which is included by `home/index.html`.

so, maybe this temp fix by Emanuele is not as bad as it looks, but we can improve helper name/ limit signature for clarity, but mechanics could be the same
